In [1]:
import numpy as np 
import pandas as pd 
import json 
import csv 
import random 

from tensorflow.keras.preprocessing.text import Tokenizer 
from tensorflow.keras.preprocessing.sequence import pad_sequences 
from tensorflow.keras.utils import to_categorical 
from tensorflow.keras import regularizers 

import pprint 
import tensorflow.compat.v1 as tf 
from tensorflow.python.framework import ops 
from sklearn.model_selection import train_test_split 
from sklearn import preprocessing 
tf.disable_eager_execution() 

# Reading the data 
data = pd.read_csv("news.csv") 
data.head() 


Unnamed: 0                                              title  \
0        8476                       You Can Smell Hillary’s Fear   
1       10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2        3608        Kerry to go to Paris in gesture of sympathy   
3       10142  Bernie supporters on Twitter erupt in anger ag...   
4         875   The Battle of New York: Why This Primary Matters   

                                                text label  
0  Daniel Greenfield, a Shillman Journalism Fello...  FAKE  
1  Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE  
2  U.S. Secretary of State John F. Kerry said Mon...  REAL  
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE  
4  It's primary day in New York and front-runners...  REAL

In [2]:
data = data.drop(["Unnamed: 0"], axis=1) 
data.head(5) 


title  \
0                       You Can Smell Hillary’s Fear   
1  Watch The Exact Moment Paul Ryan Committed Pol...   
2        Kerry to go to Paris in gesture of sympathy   
3  Bernie supporters on Twitter erupt in anger ag...   
4   The Battle of New York: Why This Primary Matters   

                                                text label  
0  Daniel Greenfield, a Shillman Journalism Fello...  FAKE  
1  Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE  
2  U.S. Secretary of State John F. Kerry said Mon...  REAL  
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE  
4  It's primary day in New York and front-runners...  REAL

In [3]:
# encoding the labels 
le = preprocessing.LabelEncoder() 
le.fit(data['label']) 
data['label'] = le.transform(data['label']) 


In [4]:
embedding_dim = 50
max_length = 54
trunc_type = 'post'
padding_type = 'post'
oov_tok = "<OOV>"
training_size = 3000
test_portion = .1


In [10]:
title = [] 
text = [] 
labels = [] 
for x in range(training_size): 
	title.append(data['title'][x]) 
	text.append(data['text'][x]) 
	labels.append(data['label'][x]) 


In [11]:
tokenizer1 = Tokenizer() 
tokenizer1.fit_on_texts(title) 
word_index1 = tokenizer1.word_index 
vocab_size1 = len(word_index1) 
sequences1 = tokenizer1.texts_to_sequences(title) 
padded1 = pad_sequences( 
	sequences1, padding=padding_type, truncating=trunc_type) 
split = int(test_portion * training_size) 
training_sequences1 = padded1[split:training_size] 
test_sequences1 = padded1[0:split] 
test_labels = labels[0:split] 
training_labels = labels[split:training_size] 


In [12]:
print(padded1)

[[  48   58 1930 ...    0    0    0]
 [ 183    1 3170 ...    0    0    0]
 [ 446    2  243 ...    0    0    0]
 ...
 [   1 7547  455 ...    0    0    0]
 [1115  321  614 ...    0    0    0]
 [   5 2516   42 ...    0    0    0]]


In [13]:
embeddings_index = {} 
with open('glove.6B.50d.txt', encoding='utf-8', errors='replace') as f: 
	for line in f: 
		values = line.split() 
		word = values[0] 
		coefs = np.asarray(values[1:], dtype='float32') 
		embeddings_index[word] = coefs 

# Generating embeddings 
embeddings_matrix = np.zeros((vocab_size1+1, embedding_dim)) 
for word, i in word_index1.items(): 
	embedding_vector = embeddings_index.get(word) 
	if embedding_vector is not None: 
		embeddings_matrix[i] = embedding_vector 


In [14]:
model = tf.keras.Sequential([ 
	tf.keras.layers.Embedding(vocab_size1+1, embedding_dim, 
							input_length=max_length, weights=[ 
								embeddings_matrix], 
							trainable=False), 
	tf.keras.layers.Dropout(0.2), 
	tf.keras.layers.Conv1D(64, 5, activation='relu'), 
	tf.keras.layers.MaxPooling1D(pool_size=4), 
	tf.keras.layers.LSTM(64), 
	tf.keras.layers.Dense(1, activation='sigmoid') 
]) 
model.compile(loss='binary_crossentropy', 
			optimizer='adam', metrics=['accuracy']) 
model.summary() 


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 54, 50)            377600    
                                                                 
 dropout (Dropout)           (None, 54, 50)            0         
                                                                 
 conv1d (Conv1D)             (None, 50, 64)            16064     
                                                                 
 max_pooling1d (MaxPooling1D  (None, 12, 64)           0         
 )                                                               
                                                                 
 lstm (LSTM)                 (None, 64)                33024     
                                                                 
 dense (Dense)               (None, 1)                 65        
                                                        

In [15]:
num_epochs = 50

training_padded = np.array(training_sequences1) 
training_labels = np.array(training_labels) 
testing_padded = np.array(test_sequences1) 
testing_labels = np.array(test_labels) 

history = model.fit(training_padded, training_labels, 
					epochs=num_epochs, 
					validation_data=(testing_padded, 
									testing_labels), 
					verbose=2) 


Train on 2700 samples, validate on 300 samples
Epoch 1/50
2700/2700 - 2s - loss: 0.6471 - accuracy: 0.6170 - val_loss: 0.5706 - val_accuracy: 0.7000 - 2s/epoch - 671us/sample


c:\Users\mahes\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training_v1.py:2335: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates = self.state_updates


Epoch 2/50
2700/2700 - 1s - loss: 0.5833 - accuracy: 0.6896 - val_loss: 0.5117 - val_accuracy: 0.7233 - 1s/epoch - 375us/sample
Epoch 3/50
2700/2700 - 1s - loss: 0.5376 - accuracy: 0.7300 - val_loss: 0.5479 - val_accuracy: 0.7200 - 969ms/epoch - 359us/sample
Epoch 4/50
2700/2700 - 1s - loss: 0.5031 - accuracy: 0.7493 - val_loss: 0.4914 - val_accuracy: 0.7400 - 984ms/epoch - 364us/sample
Epoch 5/50
2700/2700 - 1s - loss: 0.4473 - accuracy: 0.7893 - val_loss: 0.4977 - val_accuracy: 0.7700 - 979ms/epoch - 363us/sample
Epoch 6/50
2700/2700 - 1s - loss: 0.4451 - accuracy: 0.7874 - val_loss: 0.4885 - val_accuracy: 0.7733 - 972ms/epoch - 360us/sample
Epoch 7/50
2700/2700 - 1s - loss: 0.3610 - accuracy: 0.8433 - val_loss: 0.4804 - val_accuracy: 0.7667 - 987ms/epoch - 366us/sample
Epoch 8/50
2700/2700 - 1s - loss: 0.3178 - accuracy: 0.8626 - val_loss: 0.4677 - val_accuracy: 0.7867 - 1s/epoch - 374us/sample
Epoch 9/50
2700/2700 - 1s - loss: 0.2810 - accuracy: 0.8796 - val_loss: 0.4946 - val_accu

In [17]:
# sample text to check if fake or not 
X = "The Battle of New York: Why This Primary Matters"

# detection 
sequences = tokenizer1.texts_to_sequences([X])[0] 
sequences = pad_sequences([sequences], maxlen=54, 
						padding=padding_type, 
						truncating=trunc_type) 
if(model.predict(sequences, verbose=0)[0][0] >= 0.5): 
	print("This news is True") 
else: 
	print("This news is false") 	


This news is True
